# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-26 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_auto_20170326_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(max_length=200, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='event',
            name='limit',
            field=models.IntegerField(verbose_name='参加人数'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(verbose_name='发布会时间'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.BooleanField(verbose_name='状态'),
        ),
    ]
